export default {
	no_dok_lengkap: null,
	tanggal_dokumen: null,
	lppi_id: null, 
	nomor_lppi: null,
	tanggal_lppi: null,
	nomor_lpti: null,
	tanggal_lpti: null,
	nomor_npi: null,
	tanggal_npi: null,
	informasi: null,
	prosedur: null,
	hasil: null,
	kesimpulan: null,
	flag_rekom_nhi: false,
	flag_rekom_ni: false,
	rekomendasi_lain: null,
	informasi_lain: null,
	tujuan: null,
	keputusan_pejabat: true,
	catatan_pejabat: null,
	tanggal_terima_pejabat: null,
	keputusan_atasan: true,
	catatan_atasan: null,
	tanggal_terima_atasan: null,
	petugas: {
		analis: {nip: null},
		pejabat: {
			kode_jabatan: null,
			tipe_ttd: null,
			nip: null,
			flag_pejabat: true,
		},
		atasan: {
			kode_jabatan: null,
			tipe_ttd: null,
			nip: null,
			flag_pejabat: true,
		},
	}
}